### ISSUE TITLE
Enable CORS?

### ISSUE THREAD

**Issue by antgonza** [zeroapps/bashupload#10]
Thank you for https://bashupload.com/, it seems really helpful.

However, I'm trying to link one of my files with another application via CORS but it seems like it's not enabled in the server; [here](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fbashupload.com%2FGWL36%2FTwC0V.qzv&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) you can test that connectivity. 

Would it be possible to activate it?

BTW, in case it helps [here](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fview.qiime2.org%2F%3Fsrc%3Dhttps%253A%252F%252Fdocs.qiime2.org%252F2020.6%252Fdata%252Ftutorials%252Fmoving-pictures%252Fcore-metrics-results%252Funweighted_unifrac_emperor.qzv&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) is an example with CORS.

**Comment by zeroapps** [comment]
Should work now, please try it and let me know
