### ISSUE TITLE
Killed after curl 

### ISSUE THREAD

**Issue by goodguydul** [zeroapps/bashupload#11]
i got "Killed" after curl on large zip file...

**Comment by vic1707** [comment]
Got the same error, in my case it was because i didn't have enought RAM (as `--data-binary` stocks the entire file in RAM) need to use the `-T ` flag instead (and removing the `@` for some reason...)

Found the solution on https://stackoverflow.com/a/48793166

**Comment by zeroapps** [comment]
Made this a default upload method, thanks!
