### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by goodguydul** [zeroapps/bashupload#12]
![gambar](https://user-images.githubusercontent.com/48383804/92116944-b4532980-ee1e-11ea-82f0-bf0956b0e1b8.png)

500 Internal Server Error

**Comment by tech234a** [comment]
Me too

**Comment by tech234a** [comment]
Perhaps the disk or DB is full? It might clear up in a week if we're lucky.

**Comment by tech234a** [comment]
Update: it seems to be fixed for me.

**Comment by tech234a** [comment]
Hmm... it still seems to struggle with larger (ex. 70mb) uploads.

**Comment by goodguydul** [comment]
500 error on 8GB data
![gambar](https://user-images.githubusercontent.com/48383804/92388546-a7e21000-f141-11ea-8fa2-b7c4e4178fb3.png)

**Comment by zeroapps** [comment]
Try now guys, should be fixed.
